name: kubediff

on:
  pull_request:
    types:
      - opened
      - synchronize # default
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  kubediff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nakamasato/kubediff@dev
      - uses: nakamasato/typescript-action@naka-test
