name: released

on:
  release:
    types: [released]

jobs:
  deploy:
    if: github.event.release.target_commitish == 'master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: deploy
      run: |
        echo "test"
